version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: agile-requirements-tracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: agile_requirements_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: